<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

class CourseTest extends TestCase
{
    use RefreshDatabase;
    use WithoutMiddleware;
    private function admin()
    {
        $this->actingAs(factory(User::class)->create());
    }
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Event::fake();
    }
    public function test_create_course()
    {
        $this->admin();
        $response = $this->post('/courses',[
            'name'=>'Unit Test'
        ]);

        $response->assertRedirect('/courses');
    }

}
