<?php

namespace Tests\Feature;

use App\Models\Student;
use App\Repositories\Students\StudentRepository;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class FilterTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testFilter()
    {
        $studentRepository = new StudentRepository();
        $response = $studentRepository->filter([
            'filter' => 'Filter',
            'age_min' => null,
            'age_max' => null,
            'score_min' => 5,
            'score_max' => null,
        ]);
        $this->assertEquals(Student::all(), $response);
    }
}
