<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

class StudentTest extends TestCase
{
    use RefreshDatabase;
    use WithoutMiddleware;
    private function admin()
    {
        $this->actingAs(factory(User::class)->create());
    }
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Event::fake();
        // now re-register all the roles and permissions
//        $this->app->make(\Spatie\Permission\PermissionRegistrar::class)->registerPermissions();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_create_student()
    {
        $this->admin();
        $response = $this->post('/students',[
            'name' => 'TestNamesas', //required
            'birthday' => '2000-11-10', //required|date
            'email' => 'vuduydagsaa@gmail.com', //required|email|unique
            'phone' => '0911100000', //required|max:10|unique
            'gender' => '0', //0 or 1
            'course_id' => '25', //required
            'address' => 'Hoang Thanh, Hiep Hoa, Bac Giang', //null
            'avatar' => UploadedFile::fake()->image('avatar.png'), //required
            'password' => '123456' //null
        ]);

        $response->assertRedirect('/students');

    }

    public function test_update_student()
    {
        $this->admin();
        $response = $this->put('/students/2',[
            'user_id' => 2, //required
            'name' => 'TestNameEdit', //required
            'birthday' => '2019-11-10', //required
            'email' => 'vuduydagsaa@gmail.com', //required|unique
            'phone' => '0911100000', //required|unique
            'gender' => '0', //0 or 1
            'course_id' => '25', //number
            'address' => 'Hoang Thanh, Hiep Hoa, Bac Giang', //text
        ]);

//        $response->assertStatus(200);
        $response->assertRedirect('/students');
    }
}
