<?php

namespace Tests\Unit;

use App\Http\Controllers\StudentController;
use PHPUnit\Framework\TestCase;

class StudentTest extends TestCase
{
   protected $student;

   public function setUp(): void
   {
       parent::setUp(); // TODO: Change the autogenerated stub
       $this->student = new StudentController();
   }

   public function test_update_student()
   {
       $this->student->store();
   }
}
